version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/Music-Player-Using-JWT-Authentication
    overwrite: true

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu